### ISSUE TITLE
What happens to existing labels?

### ISSUE THREAD

**Issue by katrinleinweber** [fmichonneau/carpenter#1]
https://github.com/fmichonneau/carpenter/blob/92349a2aecb7ab922cce0a8c741e30bcf4fd3380/R/github_labels.R#L112

https://github.com/fmichonneau/carpenter/blob/92349a2aecb7ab922cce0a8c741e30bcf4fd3380/R/github_labels.R#L144-L154

This looks to me like existing labels will be deleted without replacement, not mapped to [the handbook's set](https://github.com/carpentries/handbook/blob/master/data/github_labels.csv). Is that true?

Because that would delete labels from the issues & PRs that the maintainers have labelled so far.

cc @tracykteal & related to https://github.com/carpentries/handbook/pull/134

**Comment by fmichonneau** [comment]
yes it is correct. It is an option to use with care.

**Comment by fmichonneau** [comment]
I should add that I switched the default to FALSE (but it's not in the repo yet).

**Comment by katrinleinweber** [comment]
Still not. Which option will you use for pushing the new labels to the repos before the Bug BBQ?

**Comment by fmichonneau** [comment]
Concerning the deployment of the new set of labels, the old ones won't be deleted unless the maintainers ask for it. The script in this repository was written with one specific situation and will be adapted depending on the context.

This script can be used by the maintainers, but it is not intended.

I try to document the process I used so it's available for future reference, to show what's possible, and for others to suggest better ways of doing things.
