### ISSUE TITLE
rename?

### ISSUE THREAD

**Issue by fmichonneau** [fmichonneau/carpenter#3]
not that this project will ever be published on CRAN, but there is already a carpenter package apparently: cran.r-project.org/package=carpenter

**Comment by zkamvar** [comment]
One side-effect of not renaming this is that anytime the user decides to update their packages, {carpenter} will be pulled from CRAN:

``` r
remotes::install_github("fmichonneau/carpenter")
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo fmichonneau/carpenter@HEAD
#> 
#>      checking for file ‘/tmp/RtmpfLr9w1/remotes519b29f67ef6/fmichonneau-carpenter-486e692/DESCRIPTION’ ...  ✔  checking for file ‘/tmp/RtmpfLr9w1/remotes519b29f67ef6/fmichonneau-carpenter-486e692/DESCRIPTION’
#>   ─  preparing ‘carpenter’:
#>      checking DESCRIPTION meta-information ...  ✔  checking DESCRIPTION meta-information
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘carpenter_0.0.0.9002.tar.gz’
#>      
#> 
#> Installing package into '/home/zhian/R/library'
#> (as 'lib' is unspecified)
packageDescription("carpenter")$Title
#> [1] "Tools to work with The Carpentries GitHub repositories"
update.packages(lib.loc = .libPaths()[1], ask = FALSE)
packageDescription("carpenter")$Title
#> [1] "Build Common Tables of Summary Statistics for Reports"
```

<sup>Created on 2020-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fmichonneau** [comment]
that's a good argument for renaming! I mostly use it with devtools and `load_all()` so I hadn't noticed this issue.

Maybe renaming it `thecarpentriestools` to make it clear that it's specific to The Carpentries and avoid metaphors that could have name clashes with other packages.

**Comment by zkamvar** [comment]
> Maybe renaming it `thecarpentriestools` to make it clear that it's specific to The Carpentries and avoid metaphors that could have name clashes with other packages.

My problem with that name is that it has 19 characters.... which is far from the average length of 7-8 characters:

``` r

 pn <- nchar(available.packages()[, "Package"])
 x <- hist(pn, breaks = 0:30)
```

![](https://i.imgur.com/8sUX2n9.png)

``` r
 dpois(x$breaks, lambda = mean(pn))[20]
#> [1] 0.0003049072
```

<sup>Created on 2020-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fmichonneau** [comment]
what do you think of "chisel"?

**Comment by zkamvar** [comment]
Me gusta

**Comment by fmichonneau** [comment]
chisel it is!
