### ISSUE TITLE
GitHub API error

### ISSUE THREAD

**Issue by DC23** [fmichonneau/carpenter#6]
When running
`create_github_labels(label_csv = "../Downloads/github_labels.csv", owner = "DC23", repo = "DC23/workflow-tests", delete_previous = TRUE)`
I get
`Parsed with column specification:
cols(
  print_order = col_double(),
  type = col_character(),
  label = col_character(),
  color = col_character(),
  use_prefix = col_logical(),
  description = col_character(),
  long_description = col_character()
)
Error in gh::gh(cmd, owner = owner, repo = repo, name = label, color = color,  : 
  GitHub API error (404): 404 Not Found
  Not Found`

While it is possible that the GitHub API has changed, I can't rule out whether this is because I am passing bad arguments to owner or repo.

Note my GitHub access token is fine.

**Comment by fmichonneau** [comment]
Hi @DC23, I think the issue here comes from the value for the `repo` argument. It should only be `workflow-tests`. Test this, and let me know if it solves your error message.

**Comment by DC23** [comment]
I get the same response:

> create_github_labels(label_csv = "../Downloads/github_labels.csv", owner = "DC23", repo = "python", delete_previous = TRUE)
> Parsed with column specification:
> cols(
>   print_order = col_double(),
>   type = col_character(),
>   label = col_character(),
>   color = col_character(),
>   use_prefix = col_logical(),
>   description = col_character(),
>   long_description = col_character()
> )
> Error in gh::gh(cmd, owner = owner, repo = repo, name = label, color = color,  : 
>   GitHub API error (404): 404 Not Found

Note I switched to a different repo. `workflow-tests` is private so I tried a public repo in case that was related.

Could it be related to the use of multi-factor authentication? Since enabling that I have been unable to write to my repos in some situations. Unfortunately I am not an R developer so I am not going to be very helpful in debugging this issue.

According to sessionInfo, I have carpenter_0.0.0.9002

**Comment by fmichonneau** [comment]
sorry for the delayed responses!

I think personal authentication tokens are independent of 2-factor authentication. 

I'm wondering if the PAT you are using has the right permissions.
Another thing to check is that the spreadsheet is correctly formatted, could you first test with the first couple of lines and if it still fails post it here or send it to me by email (francois@carpentries.org) so I can have a look in more detail?

**Comment by DC23** [comment]
Resolved. The PAT had the wrong permissions. My apologies for wasting your time with this.

**Comment by fmichonneau** [comment]
no worries, I'm glad it's working for you!
